version: '2'
services:
  jhipsteranaliseapplication-app:
    image: jhipsteranaliseapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsteranaliseapplication-postgresql:5432/jhipsterAnaliseApplication
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhipsteranaliseapplication-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhipsteranaliseapplication-elasticsearch:9200
    ports:
      - 8080:8080
  jhipsteranaliseapplication-postgresql:
    extends:
      file: postgresql.yml
      service: jhipsteranaliseapplication-postgresql
  jhipsteranaliseapplication-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhipsteranaliseapplication-elasticsearch
